# Change these first
owner: baijunyao # Your GitHub organization or username, where this repository lives
repo: status.baijunyao.com # The name of this repository

sites:
  - name: Baijunyao Blog
    url: https://baijunyao.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.baijunyao.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Baijunyao Blog
  introTitle: "**baijunyao.com** is built with laravel-bjyblog."
  introMessage: This is a sample status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
